const data = [
  {key: 1, label: 'Inventory (1)'},
  {key: 2, label: 'Low Stock'},
  {key: 3, label: 'Not In Stock'},
  {key: 4, label: 'In Stock'},
  {key: 5, label: 'Online Shop (1)'},
  {key: 6, label: 'All (1)'},
];

const PickerData = [
  'Month',
  'Year',
  'Custom',
  'Last 7 Days',
  'Today',
  'Last 30 Days',
];

// const PickerData = [
//         'Billing Type',
//         'Online Delivery sell Price',
//         'AC Sell Price',
//         'Non AC sell Price',
//       ];

const PaymentTermData = [
        'Payment Term',
        'Net 0',
        'Net 1',
        'Net 7',
        'Net 15',
        'Net 30',
        'Net 90',
      ];

const StateData = [
  'Billing State',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra & Nagar Haveli and Daman & Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Lakshadweep',
  'Puducherry',
  'Ladakh',
];

const ReceivePaymentData = ['Type', 'To Receive - Credit', 'To Pay - Balance'];

// const PaymentTermData = [
//   'Payment Term',
//   'Net 0',
//   'Net 1',
//   'Net 7',
//   'Net 15',
//   'Net 30',
//   'Net 90',
// ];

const UnitData = [
  'Unit',
  'Add Unit',
  'Pieces',
  'Box',
  'Kilograms',
  'Litre',
  'Units',
  'Bags',
  'BALE',
  'Billion of Unit',
  'Bottles',
  'Buckles',
  'Bunches',
  'Bundels',
  'Cans',
  'Cartons',
  'Centimeters',
  'Cubic Centimeters',
  'Cubic Meters',
  'Days',
  'Dozens',
  'Drums',
  'Grammes',
  'Great Gross',
  'Gross Yards',
  'Kilolitre',
  'Kilometer',
  'Meters',
  'Metric Ton',
  'MilliGram',
  'Millilitre',
  'Numbers',
  'Others',
  'Packs',
  'Pairs',
  'Quintal',
  'Rolls',
  'Sets',
  'Sq. Feet',
  'Sq. Yards',
  'Sq. Meters',
  'tablets',
  'Ten gross',
  'Thousand',
  'Tonnes',
  'Tubes',
  'US Gallons',
  'Yards',
];
